db:
  url: "/<path_to>/rss_feeds.db"

hosts:
  - url: "https://ef-magazin.de/"
    path: "?page="
    page_to: 2
    publisher: "EFMAGAZIN"
  - url: "https://freiheitsfunken.info/"
    path: "?page="
    page_to: 2
    publisher: "FREIHEITSFUNKEN"
  - url: "https://www.misesde.org/"
    path: "?_page="
    page_to: 2
    publisher: "MISESDE"
  - url: "https://hayek-institut.at/blog/"
    path: "page/"
    page_to: 2
    publisher: "HAYEK_INSTITUT"
  - url: "https://schweizermonat.ch/"
    path: "archivperlen/, dossiers/, kolumnen/, schwerpunkte/"
    page_to: 0
    publisher: "SCHWEIZER_MONAT"
  - url: "https://www.die-marktradikalen.de/blog/"
    path: "artikel/, uebersetzung/, hoerbuch/, buchvorstellung/"
    page_to: 0
    publisher: "DIE_MARKTRADIKALEN"
  - url: "https://www.dersandwirt.de/"
    path: "archiv/"
    page_to: 0
    publisher: "SANDWIRT"

concurrency: 4

rest_server:
  address: "0.0.0.0"
  port: 8989

update: "13:45"
update_interval: 24 # in hours
initial_pull: false
