redis:
  node_address: "0.0.0.0"
  port: 6379

hosts:
  efmagazin:
    url: "https://ef-magazin.de/"
    path: "?page="
    page_to: 2
  freiheitsfunken:
    url: "https://freiheitsfunken.info/"
    path: "?page="
    page_to: 2
  misesde:
    url: "https://www.misesde.org/"
    path: "?_page="
    page_to: 2

max_concurrency: 3

httpserver:
  address: "0.0.0.0"
  port: 8989

publish_interval: 86400 # 24h
