fs:
  path: "/<yourpath>/data"
  suffix: ".json"

hosts:
  efmagazin:
    url: "https://ef-magazin.de/"
    path: "?page="
    page_to: 2
  freiheitsfunken:
    url: "https://freiheitsfunken.info/"
    path: "?page="
    page_to: 2
  misesde:
    url: "https://www.misesde.org/"
    path: "?_page="
    page_to: 2
  schweizer_monat:
    url: "https://schweizermonat.ch/"
    path: "archivperlen/, dossiers/, kolumnen/, schwerpunkte/"
    page_to: 0
  hayek_institut:
    url: "https://hayek-institut.at/blog/"
    path: "page/"
    page_to: 2

max_concurrency: 5

httpserver:
  address: "0.0.0.0"
  port: 8989

update: "10:00"
